### PR TITLE
Support Python 3.9

### PR DESCRIPTION
**Pull request by decaz**

### CODE REVIEW

**Comment by decaz** [comment]
@PyYoshi should I remove Travis config or it's still actual? 3.9 build failing because Travis support only 3.9-dev version for now: https://travis-ci.org/github/PyYoshi/cChardet/builds/733612562.

**Comment by PyYoshi** [comment]
Thank you!

**Comment by PyYoshi** [comment]
> @PyYoshi should I remove Travis config or it's still actual? 3.9 build (https://travis-ci.org/github/PyYoshi/cChardet/builds/733612562) is failing because Travis supports only 3.9-dev version for now: https://docs.travis-ci.com/user/languages/python/#python-versions.

I've moved from TravisCI to GitHub Actions and will be deleting .travis.yml.
I forgot to do this. Thank you for checking :D

**Comment by decaz** [comment]
@PyYoshi can you look at #66 and release a new version on PyPI?

**Comment by decaz** [comment]
@PyYoshi can you upload cp39 wheels on PyPI?

**Comment by PyYoshi** [comment]
@decaz 
Sorry! I published it!

**Pull request merged**
